name: Minimal CI

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          pytest

      - name: Save artifact (demo)
        run: echo "This is a test artifact" > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: artifact.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: demo-artifact
      - name: Show artifact content
        run: cat artifact.txt
      - name: Deploy step
        run: echo "deployxxxxxxx"
